### ISSUE TITLE
Option to disable losing xp on teamkill. Specific for end-of-round deathmatch.

### ISSUE THREAD

**Issue by VRPCaden** [Cyanox62/PlayerXP#3]
As title says, option to disable losing xp on teamkill. Specific for end-of-round deathmatch.

**Comment by Cyanox62** [comment]
Players don't lose xp for team killing after the round ends.

**Comment by VRPCaden** [comment]
On ReddRoom I lost 200.

**Comment by overfriended** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1649452598
